language: python
install:
  - pip install ansible

services:
  - docker  

before_install:
  - docker run -d -P --name ansible-test frbk/ansible-test

script:
  - ansible-playbook -i inventory/docker main.yml
