---
- name: Update all packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: Install packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - git
      - tilix
      - gnome-tweak-tool
      - make 
      - build-essential 
      - libssl-dev 
      - zlib1g-dev 
      - libbz2-dev
      - libreadline-dev 
      - libsqlite3-dev 
      - wget 
      - curl 
      - llvm 
      - libncurses5-dev 
      - libncursesw5-dev
      - xz-utils 
      - tk-dev 
      - libffi-dev 
      - liblzma-dev
      - python-openssl
      - htop
      - gnome-shell-extension-caffeine
      - openvpn-systemd-resolved
      - network-manager-openvpn
      - network-manager-openvpn-gnome
      - dconf-editor

- name: Install classic snaps
  snap:
    name: "{{ snaps }}"
    classic: yes
  vars:
    snaps:
      - code
      - slack

- name: Install snaps
  snap:
    name: "{{ snaps }}"
    classic: yes
  vars:
    snaps:
      - discord
      - spotify  
