---

- name: Clone dotfiles
  become_user: fedor
  git:
    repo: 'git@github.com:frbk/dotfiles.git'
    dest: /home/fedor/.dotfiles

- name: Install dotfiles
  become_user: fedor
  command: /home/fedor/.dotfiles/install 
